#!/bin/bash

# # Generated by ChatGPT with this prompt:
# Please write bash code for the following steps: 1) Read json from a file called "extensions-list.json" with this content: {
#     "https://searx.fmac.xyz/": {
#         "addOnUrlName": "searxng-searx-prvcy-eu"
#     },
#     "https://searx.be/": {
#         "addOnUrlName": "searxng-searx-be"
#     },
#     "https://search.mdosch.de/": {
#         "addOnUrlName": "searxng-search-mdosch-de"
#     },
#     "https://searx.prvcy.eu/": {
#         "addOnUrlName": "searxng-searx-prvcy-eu"
#     },
#     "https://searx.tuxcloud.net/": {
#         "addOnUrlName": "searxng-searx-tuxcloud-net"
#     },
#     "https://searx.ru/": {
#         "addOnUrlName": "searxng-searx-ru"
#     },
#     "https://northboot.xyz/": {
#         "addOnUrlName": "searxng-northboot-xyz"
#     },
#     "https://searx.divided-by-zero.eu/": {
#         "addOnUrlName": "searxng-divided-by-zero-eu"
#     }
# } 2) For each of the URLs, create a string without the https:// and / at the end 3) Call a file create-extension.sh once for each of the strings with that string as argument

# Step 1: Read JSON from "extensions-list.json"
input_file="extensions-list.json"

# Check if the input file exists
if [ ! -f "$input_file" ]; then
    echo "Input file not found: $input_file"
    exit 1
fi

# Step 2: Process JSON and call x.sh for each URL
while read -r url; do
    # Remove "https://" and trailing "/" from the URL
    url_name=$(basename "$url")

    # Step 3: Call x.sh with the URL name as an argument
    ./create-extension.sh "$url_name"

done < <(jq -r 'keys[]' "$input_file")